#ifndef EVIDENCE_CPP
#define EVIDENCE_CPP
enum EvidenceEnum{
    NONE,
    KNIFE,
    BLOOD_TILE,
    BLOOD_WALL_WOOD,
    BLOOD_FOOTPRINT,
    BROKEN_PLATE,
    HAIR,
    FINGERPRINT_GLASS,
    GUNPOWDER_WALL
};
#endif
